name = "Metis Marker"
prefix = "mts"
author = "Bix, PhILoX, Timi007"
files = [
    "*.dll",
    "*.so",
    "mod.cpp",
    "README.md",
    "LICENSE",
    "mts_picture.paa",
    "mts_logo_small.paa",
    "mts_logo_over_small.paa",
    "meta.cpp"
]

modname = "Metis_Marker"
key_name = "mts_markers_{{version}}"
authority = "mts_markers_{{version}}-{{git \"id 8\"}}"

releasebuild = [
    "@zip Metis_Marker_{{semver.major}}.{{semver.minor}}.{{semver.patch}}"
]

[header_exts]
version = "{{git \"id 8\"}}"
