//Neutral Mods
MARKER(neu,mod,armor);
MARKER(neu,mod,infantry);
MARKER(neu,mod,motorized);
MARKER(neu,mod,reconnaissance);
MARKER(neu,mod,signal_unit);
MARKER(neu,mod,anti_armor);
MARKER(neu,mod,rotary_wing);
MARKER(neu,mod,uav);
MARKER(neu,mod,artillery);
MARKER(neu,mod,artillery_sp);
MARKER(neu,mod,mortar);
MARKER(neu,mod,mortar_armored);
MARKER(neu,mod,air_defence);
MARKER(neu,mod,missile);
MARKER(neu,mod,surface_surface);
MARKER(neu,mod,engineer);
MARKER(neu,mod,engineer_armored);
MARKER(neu,mod,maintenance);
MARKER(neu,mod,supply);
MARKER(neu,mod,transportation);
MARKER(neu,mod,cbrn);
MARKER(neu,mod,combat_service_support);
MARKER(neu,mod,fixed_wing);
MARKER(neu,mod,medical);
MARKER(neu,mod,military_police);
MARKER(neu,mod,military_intelligence);

//Neutral Mod1
MARKER(neu,mod,attack);
MARKER(neu,mod,air_assault);
MARKER(neu,mod,maintenance_top);
MARKER(neu,mod,multiple_rocket_launcher);
MARKER(neu,mod,single_rocket_launcher);
MARKER(neu,mod,sniper);

//Neutral Mod2
MARKER(neu,mod,airborne);
MARKER(neu,mod,mountain);
MARKER(neu,mod,light);
MARKER(neu,mod,medium);
MARKER(neu,mod,heavy);
MARKER(neu,mod,vstol);
MARKER(neu,mod,wheeled);

//Neutral Sizes
MARKER(neu,size,1);
MARKER(neu,size,2);
MARKER(neu,size,3);
MARKER(neu,size,4);
MARKER(neu,size,5);
MARKER(neu,size,6);
MARKER(neu,size,7);
MARKER(neu,size,8);
MARKER(neu,size,9);
MARKER(neu,size,10);
MARKER(neu,size,11);
MARKER(neu,size,12);

//Neutral Sizes Special
MARKER(neu,size,reinforced);
MARKER(neu,size,reduced);
MARKER(neu,size,reinforced_reduced);

//Numbers
//Left
NUMMARKER(neu,0,0);
NUMMARKER(neu,0,1);
NUMMARKER(neu,0,2);
NUMMARKER(neu,0,3);
NUMMARKER(neu,0,4);
NUMMARKER(neu,0,5);
NUMMARKER(neu,0,6);
NUMMARKER(neu,0,7);
NUMMARKER(neu,0,8);
NUMMARKER(neu,0,9);
NUMMARKER(neu,0,A);
NUMMARKER(neu,0,B);
NUMMARKER(neu,0,C);
NUMMARKER(neu,0,D);
NUMMARKER(neu,0,E);
NUMMARKER(neu,0,F);
NUMMARKER(neu,0,G);
NUMMARKER(neu,0,H);
NUMMARKER(neu,0,I);
NUMMARKER(neu,0,J);
NUMMARKER(neu,0,K);
NUMMARKER(neu,0,L);
NUMMARKER(neu,0,M);
NUMMARKER(neu,0,N);
NUMMARKER(neu,0,O);
NUMMARKER(neu,0,P);
NUMMARKER(neu,0,Q);
NUMMARKER(neu,0,R);
NUMMARKER(neu,0,S);
NUMMARKER(neu,0,T);
NUMMARKER(neu,0,U);
NUMMARKER(neu,0,V);
NUMMARKER(neu,0,W);
NUMMARKER(neu,0,X);
NUMMARKER(neu,0,Y);
NUMMARKER(neu,0,Z);

//Mid
NUMMARKER(neu,1,0);
NUMMARKER(neu,1,1);
NUMMARKER(neu,1,2);
NUMMARKER(neu,1,3);
NUMMARKER(neu,1,4);
NUMMARKER(neu,1,5);
NUMMARKER(neu,1,6);
NUMMARKER(neu,1,7);
NUMMARKER(neu,1,8);
NUMMARKER(neu,1,9);
NUMMARKER(neu,1,A);
NUMMARKER(neu,1,B);
NUMMARKER(neu,1,C);
NUMMARKER(neu,1,D);
NUMMARKER(neu,1,E);
NUMMARKER(neu,1,F);
NUMMARKER(neu,1,G);
NUMMARKER(neu,1,H);
NUMMARKER(neu,1,I);
NUMMARKER(neu,1,J);
NUMMARKER(neu,1,K);
NUMMARKER(neu,1,L);
NUMMARKER(neu,1,M);
NUMMARKER(neu,1,N);
NUMMARKER(neu,1,O);
NUMMARKER(neu,1,P);
NUMMARKER(neu,1,Q);
NUMMARKER(neu,1,R);
NUMMARKER(neu,1,S);
NUMMARKER(neu,1,T);
NUMMARKER(neu,1,U);
NUMMARKER(neu,1,V);
NUMMARKER(neu,1,W);
NUMMARKER(neu,1,X);
NUMMARKER(neu,1,Y);
NUMMARKER(neu,1,Z);

//Right
NUMMARKER(neu,2,0);
NUMMARKER(neu,2,1);
NUMMARKER(neu,2,2);
NUMMARKER(neu,2,3);
NUMMARKER(neu,2,4);
NUMMARKER(neu,2,5);
NUMMARKER(neu,2,6);
NUMMARKER(neu,2,7);
NUMMARKER(neu,2,8);
NUMMARKER(neu,2,9);
NUMMARKER(neu,2,A);
NUMMARKER(neu,2,B);
NUMMARKER(neu,2,C);
NUMMARKER(neu,2,D);
NUMMARKER(neu,2,E);
NUMMARKER(neu,2,F);
NUMMARKER(neu,2,G);
NUMMARKER(neu,2,H);
NUMMARKER(neu,2,I);
NUMMARKER(neu,2,J);
NUMMARKER(neu,2,K);
NUMMARKER(neu,2,L);
NUMMARKER(neu,2,M);
NUMMARKER(neu,2,N);
NUMMARKER(neu,2,O);
NUMMARKER(neu,2,P);
NUMMARKER(neu,2,Q);
NUMMARKER(neu,2,R);
NUMMARKER(neu,2,S);
NUMMARKER(neu,2,T);
NUMMARKER(neu,2,U);
NUMMARKER(neu,2,V);
NUMMARKER(neu,2,W);
NUMMARKER(neu,2,X);
NUMMARKER(neu,2,Y);
NUMMARKER(neu,2,Z);

//Special
NUMMARKER(neu,2,11);
NUMMARKER(neu,2,111);
NUMMARKER(neu,2,II);
NUMMARKER(neu,2,III);
