// ------------------------------------------------
// Character markers for Date-Time Group
// This file is generated and should not be edited!
// ------------------------------------------------

DTG_MARKER(0,0);
DTG_MARKER(0,1);
DTG_MARKER(0,2);
DTG_MARKER(0,3);
DTG_MARKER(0,4);
DTG_MARKER(0,5);
DTG_MARKER(0,6);
DTG_MARKER(0,7);
DTG_MARKER(0,8);
DTG_MARKER(0,9);
DTG_MARKER(0,A);
DTG_MARKER(0,B);
DTG_MARKER(0,C);
DTG_MARKER(0,D);
DTG_MARKER(0,E);
DTG_MARKER(0,F);
DTG_MARKER(0,G);
DTG_MARKER(0,H);
DTG_MARKER(0,I);
DTG_MARKER(0,J);
DTG_MARKER(0,K);
DTG_MARKER(0,L);
DTG_MARKER(0,M);
DTG_MARKER(0,N);
DTG_MARKER(0,O);
DTG_MARKER(0,P);
DTG_MARKER(0,Q);
DTG_MARKER(0,R);
DTG_MARKER(0,S);
DTG_MARKER(0,T);
DTG_MARKER(0,U);
DTG_MARKER(0,V);
DTG_MARKER(0,W);
DTG_MARKER(0,X);
DTG_MARKER(0,Y);
DTG_MARKER(0,Z);

DTG_MARKER(1,0);
DTG_MARKER(1,1);
DTG_MARKER(1,2);
DTG_MARKER(1,3);
DTG_MARKER(1,4);
DTG_MARKER(1,5);
DTG_MARKER(1,6);
DTG_MARKER(1,7);
DTG_MARKER(1,8);
DTG_MARKER(1,9);

DTG_MARKER(2,0);
DTG_MARKER(2,1);
DTG_MARKER(2,2);
DTG_MARKER(2,3);
DTG_MARKER(2,4);
DTG_MARKER(2,5);
DTG_MARKER(2,apr);
DTG_MARKER(2,aug);
DTG_MARKER(2,dec);
DTG_MARKER(2,feb);
DTG_MARKER(2,jan);
DTG_MARKER(2,jul);
DTG_MARKER(2,jun);
DTG_MARKER(2,mar);
DTG_MARKER(2,may);
DTG_MARKER(2,nov);
DTG_MARKER(2,oct);
DTG_MARKER(2,sep);

DTG_MARKER(3,0);
DTG_MARKER(3,1);
DTG_MARKER(3,2);
DTG_MARKER(3,3);
DTG_MARKER(3,4);
DTG_MARKER(3,5);
DTG_MARKER(3,6);
DTG_MARKER(3,7);
DTG_MARKER(3,8);
DTG_MARKER(3,9);

DTG_MARKER(4,0);
DTG_MARKER(4,1);
DTG_MARKER(4,2);

DTG_MARKER(5,A);
DTG_MARKER(5,B);
DTG_MARKER(5,C);
DTG_MARKER(5,D);
DTG_MARKER(5,E);
DTG_MARKER(5,F);
DTG_MARKER(5,G);
DTG_MARKER(5,H);
DTG_MARKER(5,I);
DTG_MARKER(5,J);
DTG_MARKER(5,K);
DTG_MARKER(5,L);
DTG_MARKER(5,M);
DTG_MARKER(5,N);
DTG_MARKER(5,O);
DTG_MARKER(5,P);
DTG_MARKER(5,Q);
DTG_MARKER(5,R);
DTG_MARKER(5,S);
DTG_MARKER(5,T);
DTG_MARKER(5,U);
DTG_MARKER(5,V);
DTG_MARKER(5,W);
DTG_MARKER(5,X);
DTG_MARKER(5,Y);
DTG_MARKER(5,Z);

DTG_MARKER(6,0);
DTG_MARKER(6,1);
DTG_MARKER(6,2);
DTG_MARKER(6,3);
DTG_MARKER(6,4);
DTG_MARKER(6,5);
DTG_MARKER(6,6);
DTG_MARKER(6,7);
DTG_MARKER(6,8);
DTG_MARKER(6,9);

DTG_MARKER(7,0);
DTG_MARKER(7,1);
DTG_MARKER(7,2);
DTG_MARKER(7,3);
DTG_MARKER(7,4);
DTG_MARKER(7,5);

DTG_MARKER(8,0);
DTG_MARKER(8,1);
DTG_MARKER(8,2);
DTG_MARKER(8,3);
DTG_MARKER(8,4);
DTG_MARKER(8,5);
DTG_MARKER(8,6);
DTG_MARKER(8,7);
DTG_MARKER(8,8);
DTG_MARKER(8,9);

DTG_MARKER(9,0);
DTG_MARKER(9,1);
DTG_MARKER(9,2);

DTG_MARKER(10,0);
DTG_MARKER(10,1);
DTG_MARKER(10,2);
DTG_MARKER(10,3);
DTG_MARKER(10,4);
DTG_MARKER(10,5);
DTG_MARKER(10,6);
DTG_MARKER(10,7);
DTG_MARKER(10,8);
DTG_MARKER(10,9);

DTG_MARKER(11,0);
DTG_MARKER(11,1);
DTG_MARKER(11,2);
DTG_MARKER(11,3);

