// ------------------------------------------------
// Character markers for Date-Time Group
// This file is generated and should not be edited!
// ------------------------------------------------

DTGMARKER(0,0);
DTGMARKER(0,1);
DTGMARKER(0,2);
DTGMARKER(0,3);
DTGMARKER(0,4);
DTGMARKER(0,5);
DTGMARKER(0,6);
DTGMARKER(0,7);
DTGMARKER(0,8);
DTGMARKER(0,9);
DTGMARKER(0,A);
DTGMARKER(0,B);
DTGMARKER(0,C);
DTGMARKER(0,D);
DTGMARKER(0,E);
DTGMARKER(0,F);
DTGMARKER(0,G);
DTGMARKER(0,H);
DTGMARKER(0,I);
DTGMARKER(0,J);
DTGMARKER(0,K);
DTGMARKER(0,L);
DTGMARKER(0,M);
DTGMARKER(0,N);
DTGMARKER(0,O);
DTGMARKER(0,P);
DTGMARKER(0,Q);
DTGMARKER(0,R);
DTGMARKER(0,S);
DTGMARKER(0,T);
DTGMARKER(0,U);
DTGMARKER(0,V);
DTGMARKER(0,W);
DTGMARKER(0,X);
DTGMARKER(0,Y);
DTGMARKER(0,Z);

DTGMARKER(1,0);
DTGMARKER(1,1);
DTGMARKER(1,2);
DTGMARKER(1,3);
DTGMARKER(1,4);
DTGMARKER(1,5);
DTGMARKER(1,6);
DTGMARKER(1,7);
DTGMARKER(1,8);
DTGMARKER(1,9);

DTGMARKER(2,0);
DTGMARKER(2,1);
DTGMARKER(2,2);
DTGMARKER(2,3);
DTGMARKER(2,4);
DTGMARKER(2,5);
DTGMARKER(2,apr);
DTGMARKER(2,aug);
DTGMARKER(2,dec);
DTGMARKER(2,feb);
DTGMARKER(2,jan);
DTGMARKER(2,jul);
DTGMARKER(2,jun);
DTGMARKER(2,mar);
DTGMARKER(2,may);
DTGMARKER(2,nov);
DTGMARKER(2,oct);
DTGMARKER(2,sep);

DTGMARKER(3,0);
DTGMARKER(3,1);
DTGMARKER(3,2);
DTGMARKER(3,3);
DTGMARKER(3,4);
DTGMARKER(3,5);
DTGMARKER(3,6);
DTGMARKER(3,7);
DTGMARKER(3,8);
DTGMARKER(3,9);

DTGMARKER(4,0);
DTGMARKER(4,1);
DTGMARKER(4,2);

DTGMARKER(5,A);
DTGMARKER(5,B);
DTGMARKER(5,C);
DTGMARKER(5,D);
DTGMARKER(5,E);
DTGMARKER(5,F);
DTGMARKER(5,G);
DTGMARKER(5,H);
DTGMARKER(5,I);
DTGMARKER(5,J);
DTGMARKER(5,K);
DTGMARKER(5,L);
DTGMARKER(5,M);
DTGMARKER(5,N);
DTGMARKER(5,O);
DTGMARKER(5,P);
DTGMARKER(5,Q);
DTGMARKER(5,R);
DTGMARKER(5,S);
DTGMARKER(5,T);
DTGMARKER(5,U);
DTGMARKER(5,V);
DTGMARKER(5,W);
DTGMARKER(5,X);
DTGMARKER(5,Y);
DTGMARKER(5,Z);

DTGMARKER(6,0);
DTGMARKER(6,1);
DTGMARKER(6,2);
DTGMARKER(6,3);
DTGMARKER(6,4);
DTGMARKER(6,5);
DTGMARKER(6,6);
DTGMARKER(6,7);
DTGMARKER(6,8);
DTGMARKER(6,9);

DTGMARKER(7,0);
DTGMARKER(7,1);
DTGMARKER(7,2);
DTGMARKER(7,3);
DTGMARKER(7,4);
DTGMARKER(7,5);

DTGMARKER(8,0);
DTGMARKER(8,1);
DTGMARKER(8,2);
DTGMARKER(8,3);
DTGMARKER(8,4);
DTGMARKER(8,5);
DTGMARKER(8,6);
DTGMARKER(8,7);
DTGMARKER(8,8);
DTGMARKER(8,9);

DTGMARKER(9,0);
DTGMARKER(9,1);
DTGMARKER(9,2);

DTGMARKER(10,0);
DTGMARKER(10,1);
DTGMARKER(10,2);
DTGMARKER(10,3);
DTGMARKER(10,4);
DTGMARKER(10,5);
DTGMARKER(10,6);
DTGMARKER(10,7);
DTGMARKER(10,8);
DTGMARKER(10,9);

DTGMARKER(11,0);
DTGMARKER(11,1);
DTGMARKER(11,2);
DTGMARKER(11,3);

