// ------------------------------------------------
// Character markers for Date-Time Group
// This file is generated and should not be edited!
// ------------------------------------------------

DTGMARKER(0,0);
DTGMARKER(0,1);
DTGMARKER(0,2);
DTGMARKER(0,3);
DTGMARKER(0,4);
DTGMARKER(0,5);
DTGMARKER(0,6);
DTGMARKER(0,7);
DTGMARKER(0,8);
DTGMARKER(0,9);

DTGMARKER(1,0);
DTGMARKER(1,1);
DTGMARKER(1,2);
DTGMARKER(1,3);
DTGMARKER(1,4);
DTGMARKER(1,5);
DTGMARKER(1,6);
DTGMARKER(1,7);
DTGMARKER(1,8);
DTGMARKER(1,9);

DTGMARKER(2,jan);
DTGMARKER(2,feb);
DTGMARKER(2,mar);
DTGMARKER(2,apr);
DTGMARKER(2,may);
DTGMARKER(2,jun);
DTGMARKER(2,jul);
DTGMARKER(2,aug);
DTGMARKER(2,sep);
DTGMARKER(2,oct);
DTGMARKER(2,nov);
DTGMARKER(2,dec);

DTGMARKER(3,A);
DTGMARKER(3,B);
DTGMARKER(3,C);
DTGMARKER(3,D);
DTGMARKER(3,E);
DTGMARKER(3,F);
DTGMARKER(3,G);
DTGMARKER(3,H);
DTGMARKER(3,I);
DTGMARKER(3,J);
DTGMARKER(3,K);
DTGMARKER(3,L);
DTGMARKER(3,M);
DTGMARKER(3,N);
DTGMARKER(3,O);
DTGMARKER(3,P);
DTGMARKER(3,Q);
DTGMARKER(3,R);
DTGMARKER(3,S);
DTGMARKER(3,T);
DTGMARKER(3,U);
DTGMARKER(3,V);
DTGMARKER(3,W);
DTGMARKER(3,X);
DTGMARKER(3,Y);
DTGMARKER(3,Z);

DTGMARKER(4,0);
DTGMARKER(4,1);
DTGMARKER(4,2);
DTGMARKER(4,3);
DTGMARKER(4,4);
DTGMARKER(4,5);
DTGMARKER(4,6);
DTGMARKER(4,7);
DTGMARKER(4,8);
DTGMARKER(4,9);

DTGMARKER(5,0);
DTGMARKER(5,1);
DTGMARKER(5,2);
DTGMARKER(5,3);
DTGMARKER(5,4);
DTGMARKER(5,5);

DTGMARKER(6,0);
DTGMARKER(6,1);
DTGMARKER(6,2);
DTGMARKER(6,3);
DTGMARKER(6,4);
DTGMARKER(6,5);
DTGMARKER(6,6);
DTGMARKER(6,7);
DTGMARKER(6,8);
DTGMARKER(6,9);

DTGMARKER(7,0);
DTGMARKER(7,1);
DTGMARKER(7,2);

DTGMARKER(8,0);
DTGMARKER(8,1);
DTGMARKER(8,2);
DTGMARKER(8,3);
DTGMARKER(8,4);
DTGMARKER(8,5);
DTGMARKER(8,6);
DTGMARKER(8,7);
DTGMARKER(8,8);
DTGMARKER(8,9);

DTGMARKER(9,0);
DTGMARKER(9,1);
DTGMARKER(9,2);
DTGMARKER(9,3);

